[package]
name = "mopaq"
version = "0.1.0"
authors = ["Daniel S. Reichenbach <daniel@kogito.network>"]
edition = "2024"
rust-version = "1.86"
description = "MoPaQ implementation in Rust"
repository = "https://github.com/danielsreichenbach/mopaq"
license = "MIT OR Apache-2.0"
keywords = ["archive", "compression", "mpq"]

[dependencies]
byteorder = "1.5"
memmap2 = "0.9"
thiserror = "2.0"
clap = { version = "4.5", features = ["color", "derive"] }
indicatif = "0.17"

[dev-dependencies]
criterion = "0.5"
tempfile = "3.19"

[[bench]]
name = "header_benchmark"
harness = false
