# deny.toml - Configuration for cargo-deny

[graph]
targets = [
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
  { triple = "x86_64-pc-windows-msvc" },
  { triple = "x86_64-apple-darwin" },
  { triple = "aarch64-apple-darwin" },
]

[advisories]
# The path where advisory databases are cloned/fetched
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# Threshold for security vulnerabilities
vulnerability = "deny"
# Threshold for unmaintained crates
unmaintained = "warn"
# Allow crates with security notices
notice = "warn"
# Ignore specific advisories
ignore = []

[licenses]
# List of allowed licenses
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-DFS-2016",
  "CC0-1.0",
]
# Deny specific licenses
deny = ["GPL-2.0", "GPL-3.0", "AGPL-3.0"]
# Copyleft licenses require manual review
copyleft = "warn"
# Allow licenses in the confidence range
confidence-threshold = 0.8
# Allow multiple versions of a crate with different licenses
allow-osi-fsf-free = "both"

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
# Deny wildcard dependencies
wildcards = "deny"
# Don't allow crates with build scripts for certain use cases
allow-build-scripts = ["proc-macro2", "proc-macro-error-attr"]
# Highlight certain crates
highlight = "all"
# Skip certain crates when checking for duplicates
skip = []
# Skip entire tree of certain crates when checking for duplicates
skip-tree = []
# Deny specific crates
deny = [
  # Example of denying an old, deprecated crate
  # { name = "openssl", version = "*" }
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not in the allow list is encountered
unknown-git = "warn"
# List of allowed crate registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []
