# Rustfmt configuration for StormLib-rs

edition = "2021"
max_width = 100
use_small_heuristics = "Default"
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Comments and documentation
normalize_comments = true
wrap_comments = true
format_code_in_doc_comments = true

# Other formatting options
use_field_init_shorthand = true
use_try_shorthand = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

# Preserve formatting in certain cases
trailing_comma = "Vertical"
match_block_trailing_comma = true
overflow_delimited_expr = true
