#ifndef STORMLIB_H
#define STORMLIB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Generated with cbindgen:0.29.0 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// CRC32 checksums are present
#define AttributeFlags_CRC32 1

// File timestamps are present
#define AttributeFlags_FILETIME 2

// MD5 hashes are present
#define AttributeFlags_MD5 4

// Patch bit indicators are present
#define AttributeFlags_PATCH_BIT 8

// All attributes are present
#define AttributeFlags_ALL 15

// Expected version for the attributes file
#define Attributes_EXPECTED_VERSION 100

// Archive handle type
typedef void *HANDLE;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Open an MPQ archive
//
// # Safety
//
// - `filename` must be a valid null-terminated C string
// - `handle` must be a valid pointer to write the output handle
bool SFileOpenArchive(const char *filename, uint32_t _priority, uint32_t _flags, HANDLE *handle);

// Create a new MPQ archive
//
// # Safety
//
// - `filename` must be a valid null-terminated C string
// - `handle` must be a valid pointer to write the output handle
bool SFileCreateArchive(const char *filename,
                        uint32_t creation_disposition,
                        uint32_t hash_table_size,
                        HANDLE *handle);

// Close an MPQ archive
bool SFileCloseArchive(HANDLE handle);

// Open a file in the archive
//
// # Safety
//
// - `filename` must be a valid null-terminated C string
// - `file_handle` must be a valid pointer to write the output handle
bool SFileOpenFileEx(HANDLE archive,
                     const char *filename,
                     uint32_t _search_scope,
                     HANDLE *file_handle);

// Close a file
bool SFileCloseFile(HANDLE file);

// Read from a file
//
// # Safety
//
// - `buffer` must be a valid pointer with at least `to_read` bytes available
// - `read` if not null, must be a valid pointer to write the bytes read
bool SFileReadFile(HANDLE file, void *buffer, uint32_t to_read, uint32_t *read, void *_overlapped);

// Get file size
//
// # Safety
//
// - `high` if not null, must be a valid pointer to write the high 32 bits
uint32_t SFileGetFileSize(HANDLE file, uint32_t *high);

// Set file position
//
// # Safety
//
// - `file_pos_high` if not null, must be a valid pointer to read/write the high 32 bits
uint32_t SFileSetFilePointer(HANDLE file,
                             int32_t file_pos,
                             int32_t *file_pos_high,
                             uint32_t move_method);

// Check if file exists in archive
//
// # Safety
//
// - `filename` must be a valid null-terminated C string
bool SFileHasFile(HANDLE archive, const char *filename);

// Get file information
//
// # Safety
//
// - `buffer` if not null, must be a valid pointer with at least `buffer_size` bytes
// - `size_needed` if not null, must be a valid pointer to write the required size
bool SFileGetFileInfo(HANDLE file_or_archive,
                      uint32_t info_class,
                      void *buffer,
                      uint32_t buffer_size,
                      uint32_t *size_needed);

// Get archive name from handle
//
// # Safety
//
// - `buffer` must be a valid pointer with at least `buffer_size` bytes available
bool SFileGetArchiveName(HANDLE archive, char *buffer, uint32_t buffer_size);

// Enumerate files in archive
//
// # Safety
//
// - `search_mask` if not null, must be a valid null-terminated C string
// - `_list_file` if not null, must be a valid null-terminated C string (ignored)
// - `callback` function pointer must be valid for the duration of enumeration
bool SFileEnumFiles(HANDLE archive,
                    const char *search_mask,
                    const char *_list_file,
                    bool (*callback)(const char*, void*),
                    void *user_data);

// Set locale for file operations
uint32_t SFileSetLocale(uint32_t locale);

// Get current locale
uint32_t SFileGetLocale(void);

// Get last error
uint32_t SFileGetLastError(void);

// Set last error
void SFileSetLastError(uint32_t error);

// Get file name from handle
//
// # Safety
//
// - `buffer` must be a valid pointer with sufficient space for the filename
bool SFileGetFileName(HANDLE file, char *buffer);

// Extract a file from archive to disk
//
// # Safety
//
// - `filename` must be a valid null-terminated C string
// - `local_filename` must be a valid null-terminated C string
bool SFileExtractFile(HANDLE archive,
                      const char *filename,
                      const char *local_filename,
                      uint32_t _search_scope);

// Verify file integrity
//
// # Safety
//
// - `filename` must be a valid null-terminated C string
bool SFileVerifyFile(HANDLE archive, const char *filename, uint32_t flags);

// Verify archive integrity
bool SFileVerifyArchive(HANDLE archive, uint32_t flags);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus


#ifdef __cplusplus
}
#endif

#endif /* STORMLIB_H */
