#ifndef STORMLIB_H
#define STORMLIB_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* Generated with cbindgen:0.27.0 */

/* Warning: This file is auto-generated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// Archive handle type
typedef void *HANDLE;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Open an MPQ archive
bool SFileOpenArchive(const char *_filename, uint32_t _priority, uint32_t _flags, HANDLE *_handle);

// Close an MPQ archive
bool SFileCloseArchive(HANDLE _handle);

// Open a file in the archive
bool SFileOpenFileEx(HANDLE _archive,
                     const char *_filename,
                     uint32_t _search_scope,
                     HANDLE *_file_handle);

// Close a file
bool SFileCloseFile(HANDLE _file);

// Read from a file
bool SFileReadFile(HANDLE _file,
                   void *_buffer,
                   uint32_t _to_read,
                   uint32_t *_read,
                   void *_overlapped);

// Get file size
uint32_t SFileGetFileSize(HANDLE _file, uint32_t *_high);

// Get last error
uint32_t GetLastError(void);

// Set last error
void SetLastError(uint32_t _error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus


#ifdef __cplusplus
}
#endif

#endif /* STORMLIB_H */
