name: Cross-Platform Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  matrix-setup:
    name: Setup Build Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix=$(cat <<EOF
          {
            "include": [
              {"target": "x86_64-unknown-linux-gnu", "os": "ubuntu-latest", "cross": false},
              {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-latest", "cross": true},
              {"target": "aarch64-unknown-linux-gnu", "os": "ubuntu-latest", "cross": true},
              {"target": "x86_64-pc-windows-msvc", "os": "windows-latest", "cross": false},
              {"target": "aarch64-apple-darwin", "os": "macos-latest", "cross": false}
            ]
          }
          EOF
          )
          echo "matrix=$(echo $matrix | jq -c .)" >> $GITHUB_OUTPUT

  cross-build:
    name: Build ${{ matrix.target }}
    needs: matrix-setup
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix-setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'cross-${{ matrix.target }}'

      # Use cross for Linux cross-compilation
      - name: Install cross
        if: matrix.cross && matrix.os == 'ubuntu-latest'
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      # Build with cross
      - name: Build with cross
        if: matrix.cross
        run: |
          cross build --target ${{ matrix.target }} --release --package storm-cli
          cross build --target ${{ matrix.target }} --release --package storm-ffi

      # Build natively
      - name: Build natively
        if: '!matrix.cross'
        run: |
          cargo build --target ${{ matrix.target }} --release --package storm-cli
          cargo build --target ${{ matrix.target }} --release --package storm-ffi

      # Test build artifacts exist
      - name: Verify build artifacts
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            ls -la target/${{ matrix.target }}/release/*.exe || true
            ls -la target/${{ matrix.target }}/release/*.dll || true
          else
            ls -la target/${{ matrix.target }}/release/storm-cli || true
            ls -la target/${{ matrix.target }}/release/*.so || ls -la target/${{ matrix.target }}/release/*.dylib || true
          fi

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/storm-cli*
            target/${{ matrix.target }}/release/*storm_ffi*
          if-no-files-found: error

  build-wasm:
    name: WebAssembly Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM
        run: |
          # Create a minimal wrapper crate for WASM
          mkdir -p mopaq-wasm/src
          cat > mopaq-wasm/Cargo.toml <<EOF
          [package]
          name = "mopaq-wasm"
          version = "0.1.0"
          edition = "2021"

          [dependencies]
          mopaq = { path = "../mopaq", default-features = false }
          wasm-bindgen = "0.2"

          [lib]
          crate-type = ["cdylib"]
          EOF

          cat > mopaq-wasm/src/lib.rs <<EOF
          use wasm_bindgen::prelude::*;

          #[wasm_bindgen]
          pub fn version() -> String {
              env!("CARGO_PKG_VERSION").to_string()
          }
          EOF

          cd mopaq-wasm
          wasm-pack build --target web

      - name: Upload WASM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: mopaq-wasm/pkg/
