name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_BACKTRACE: 1

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: Release v${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false

  # Build all binaries in parallel
  build-binaries:
    name: Build (${{ matrix.target }})
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux builds using cross for better compatibility
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            binary: storm-cli
            use_cross: true
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            binary: storm-cli
            use_cross: true
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            binary: storm-cli
            use_cross: true
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            binary: storm-cli
            use_cross: true

          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            binary: storm-cli.exe
            use_cross: false

          # macOS
          - target: aarch64-apple-darwin
            os: macos-latest
            binary: storm-cli
            use_cross: false
          - target: x86_64-apple-darwin
            os: macos-latest
            binary: storm-cli
            use_cross: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'release-${{ matrix.target }}'
          cache-on-failure: true

      # Install cross for Linux builds
      - name: Install cross
        if: matrix.use_cross == true
        run: |
          # Use cargo-binstall for faster installation if available
          if command -v cargo-binstall >/dev/null 2>&1; then
            cargo binstall --no-confirm cross
          else
            cargo install cross --git https://github.com/cross-rs/cross
          fi

      # Build using cross or cargo
      - name: Build release binary
        run: |
          if [[ "${{ matrix.use_cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }} --package storm-cli
          else
            cargo build --release --target ${{ matrix.target }} --package storm-cli
          fi
        shell: bash

      - name: Package binary
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../storm-cli-${{ matrix.target }}.zip ${{ matrix.binary }}
          else
            tar czf ../../../storm-cli-${{ matrix.target }}.tar.gz ${{ matrix.binary }}
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: storm-cli-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_name: storm-cli-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: ${{ matrix.os == 'windows-latest' && 'application/zip' || 'application/gzip' }}

  # Build FFI libraries in parallel
  build-ffi:
    name: Build FFI (${{ matrix.target }})
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            use_cross: true
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            use_cross: true
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            use_cross: false
          - target: x86_64-apple-darwin
            os: macos-latest
            use_cross: false
          - target: aarch64-apple-darwin
            os: macos-latest
            use_cross: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'release-ffi-${{ matrix.target }}'
          cache-on-failure: true

      # Install cross for Linux builds
      - name: Install cross
        if: matrix.use_cross == true
        run: |
          if command -v cargo-binstall >/dev/null 2>&1; then
            cargo binstall --no-confirm cross
          else
            cargo install cross --git https://github.com/cross-rs/cross
          fi

      # Build FFI library
      - name: Build FFI library
        run: |
          if [[ "${{ matrix.use_cross }}" == "true" ]]; then
            cross build --release --target ${{ matrix.target }} --package storm-ffi
          else
            cargo build --release --target ${{ matrix.target }} --package storm-ffi
          fi
        shell: bash

      - name: Package library
        shell: bash
        run: |
          mkdir -p storm-ffi-${{ matrix.target }}
          cp storm-ffi/include/StormLib.h storm-ffi-${{ matrix.target }}/

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/storm_ffi.dll storm-ffi-${{ matrix.target }}/
            cp target/${{ matrix.target }}/release/storm_ffi.dll.lib storm-ffi-${{ matrix.target }}/
            7z a storm-ffi-${{ matrix.target }}.zip storm-ffi-${{ matrix.target }}/*
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp target/${{ matrix.target }}/release/libstorm_ffi.dylib storm-ffi-${{ matrix.target }}/
            tar czf storm-ffi-${{ matrix.target }}.tar.gz storm-ffi-${{ matrix.target }}
          else
            cp target/${{ matrix.target }}/release/libstorm_ffi.so storm-ffi-${{ matrix.target }}/
            tar czf storm-ffi-${{ matrix.target }}.tar.gz storm-ffi-${{ matrix.target }}
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: storm-ffi-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_name: storm-ffi-${{ matrix.target }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
          asset_content_type: ${{ matrix.os == 'windows-latest' && 'application/zip' || 'application/gzip' }}

  # Publish to crates.io after binaries are built
  publish-crates:
    name: Publish to crates.io
    needs: [build-binaries, build-ffi]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'publish'
          cache-on-failure: true

      # Publish in dependency order
      - name: Publish mopaq
        run: cargo publish --package mopaq --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Wait for crates.io propagation
        run: |
          echo "Waiting for mopaq to be available on crates.io..."
          for i in {1..60}; do
            if cargo search mopaq --limit 1 | grep -q "^mopaq "; then
              echo "mopaq is now available!"
              break
            fi
            echo "Attempt $i/60: Waiting..."
            sleep 5
          done

      - name: Publish storm-ffi
        run: cargo publish --package storm-ffi --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        continue-on-error: true

      - name: Wait for crates.io propagation
        run: |
          echo "Waiting for storm-ffi to be available on crates.io..."
          for i in {1..60}; do
            if cargo search storm-ffi --limit 1 | grep -q "^storm-ffi "; then
              echo "storm-ffi is now available!"
              break
            fi
            echo "Attempt $i/60: Waiting..."
            sleep 5
          done

      - name: Publish storm-cli
        run: cargo publish --package storm-cli --no-verify
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
